// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NLP_CAPTCHA_APP.ApiService.Migrations
{
    [DbContext(typeof(CaptchaDbContext))]
    [Migration("20251106155306_FinalSchema")]
    partial class FinalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CaptchaSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSentenceId");

                    b.ToTable("CaptchaSentences");
                });

            modelBuilder.Entity("OriginalSentence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Task_input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Task_output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Task_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesMarkedAsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesProposed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OriginalSentences");
                });

            modelBuilder.Entity("SubmissionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("InteractionTimeInSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("OriginalSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedWord")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasMarkedAsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WordPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubmissionLogs");
                });

            modelBuilder.Entity("SuggestedCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SuggestedCorrections");
                });

            modelBuilder.Entity("CaptchaSentence", b =>
                {
                    b.HasOne("OriginalSentence", "OriginalSentence")
                        .WithMany()
                        .HasForeignKey("OriginalSentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalSentence");
                });
#pragma warning restore 612, 618
        }
    }
}
